kan_schema = "board/2"
id = "2R9nzEvz"
name = "main"
default_column = "backlog-hi"

[[columns]]
  name = "backlog-lo"
  color = "#9333ea"
  card_ids = ["2REAnxC6", "2REBORtt", "2RERa5et", "2RESVvds", "2RF0aoHq", "2RR0gW1U", "2RMKzF8A", "32mUefF1", "32odHmOO", "a_6OLXA9WA"]

[[columns]]
  name = "backlog-hi"
  color = "#6b7280"
  card_ids = ["3cIruBkr", "2RF2RcyA", "48AVDad4", "2REB6NLa", "2REBgzSK", "2RESoTin", "2RET9h3a", "2RF1gl2S", "2RF25n0b", "4CWvz4xq", "a_6NBw2rbK", "a_6NPbhW3o", "a_BlWLznge", "4CXN7HhS", "a_EX5Arv9h"]

[[columns]]
  name = "next"
  color = "#3b82f6"
  card_ids = ["3cJmN0qU", "a_6NhrwFOp", "4CUbhFTJ", "3dav9GZU", "a_EYZAQKps"]

[[columns]]
  name = "in-progress"
  color = "#f59e0b"

[[columns]]
  name = "done"
  color = "#10b981"
  card_ids = ["3c900E57", "48O31Ctb", "a_DnJXCAIr", "a_6NrXm5Ky", "a_6NqOp49M", "a_6NpX7nrE", "4CP22Hzt", "a_6Nfme0TU", "2RFKjwYX", "a_8o62zhUu", "a_8o1jyZN8", "5utsN5st", "3cKIYh0p", "3d1MfWZS", "3d58C4UJ", "48P2Qpfg", "48OWoX57", "2RESD2LM", "48NdHhpT", "2REATGIR", "32uFMcPs", "2RdBBLnA", "2RF195UV", "2RERulDq", "2REA5mCQ", "2RFLL8mC", "2RFLeA3b", "2RFLw7h8", "2RFL3u0o", "31FtC9Qq", "31jSrye7"]

[custom_fields]
  [custom_fields.type]
    type = "enum"

    [[custom_fields.type.options]]
      value = "bug"
      color = "#dc2626"

    [[custom_fields.type.options]]
      value = "enhancement"
      color = "#2563eb"

    [[custom_fields.type.options]]
      value = "feature"
      color = "#16a34a"

    [[custom_fields.type.options]]
      value = "chore"
      color = "#4b5563"

[card_display]
  type_indicator = "type"
